# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/gene.rb'

Hoe.new('gene', Gene::VERSION) do |p|
  # p.rubyforge_name = 'genex' # if different than lowercase project name
  p.developer('Evan Senter', 'evansenter@gmail.com')
end

# vim: syntax=Ruby
